# Generated by Django 6.1 on 2026-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='image',
            new_name='primary_image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='items_images/'),
        ),
    ]
