# Generated by Django 6.1 on 2026-10-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_image_itemimage_primary_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='primary_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='secondary_image',
        ),
    ]
